/*
Data Generated By - SQLyog Enterprise v4.06
*/

use `servi_ot`;

create table `servi_ot`.`actividades` ( 
 	`id_actividad` int (10)   NOT NULL ,
	`descrip` varchar (250)   NOT NULL  ,
	PRIMARY KEY ( `id_actividad` ) 
);
create table `servi_ot`.`clientes` ( 
 	`nitced` int (10)   NOT NULL ,
	`nombre` varchar (80)   NOT NULL ,
	`direccion` varchar (80)   NOT NULL ,
	`celular` varchar (50)   NOT NULL ,
	`correo` varchar (80)   NOT NULL ,
	`estado` int (10)   NOT NULL  ,
	PRIMARY KEY ( `nitced` ) 
);
create table `servi_ot`.`equipos` ( 
 	`id_equipo` varchar (10)   NOT NULL ,
	`tipo_equipo` decimal   NOT NULL ,
	`nitced` int (10)   NOT NULL ,
	`id_refrigerante` int (10)   NOT NULL ,
	`fecha_instalacion` datetime   NOT NULL ,
	`fecha_garantia` datetime   NOT NULL ,
	`estado` decimal   NOT NULL ,
	`altura` decimal   NULL ,
	`ancho` decimal   NULL ,
	`profundidad` decimal   NULL  ,
	PRIMARY KEY ( `id_equipo` ) 
);
create table `servi_ot`.`ot` ( 
 	`consecutivo` int (10)   NOT NULL ,
	`tipo` decimal   NOT NULL ,
	`fecha` datetime   NOT NULL ,
	`fecha_venc` datetime   NOT NULL ,
	`id_equipo` varchar (10)   NOT NULL ,
	`nitCliente` int (10)   NOT NULL ,
	`observa_antes` varchar (250)   NOT NULL ,
	`observa_despues` varchar (250)   NOT NULL ,
	`prioridad` int (10)   NOT NULL ,
	`ok_cliente` decimal   NOT NULL ,
	`id_usuario` varchar (20)   NULL  ,
	PRIMARY KEY ( `consecutivo` ) 
);
create table `servi_ot`.`otDetalle` ( 
 	`consecutivo` int (10)   NOT NULL ,
	`id_actividad` int (10)   NOT NULL ,
	`resp_actividad` varchar (80)   NOT NULL ,
	`id` int (10)   NOT NULL  ,
	PRIMARY KEY ( `id` ) 
);
create table `servi_ot`.`refrigerante` ( 
 	`id_refrigerante` int (10)   NOT NULL ,
	`nombRefrigerante` varchar (50)   NOT NULL  ,
	PRIMARY KEY ( `id_refrigerante` ) 
);
create table `servi_ot`.`respuestos` ( 
 	`id_repuesto` varchar (10)   NOT NULL ,
	`nombRepuesto` varchar (80)   NULL ,
	`referencia` varchar (30)   NULL  ,
	PRIMARY KEY ( `id_repuesto` ) 
);
create table `servi_ot`.`sysdiagrams` ( 
 	`name` varchar (128)   NOT NULL ,
	`principal_id` int (10)   NOT NULL ,
	`diagram_id` int (10)   NOT NULL ,
	`version` int (10)   NULL ,
	`definition` blob   NULL  ,
	PRIMARY KEY ( `diagram_id` ) 
);
create table `servi_ot`.`tecnicoAsignado` ( 
 	`consecutivo` int (10)   NOT NULL ,
	`cedula` int (10)   NOT NULL ,
	`id` int (10)   NOT NULL  ,
	PRIMARY KEY ( `id` ) 
);
create table `servi_ot`.`tecnicos` ( 
 	`cedula` int (10)   NOT NULL ,
	`nombre` varchar (80)   NOT NULL ,
	`celular` varchar (50)   NULL ,
	`correo` varchar (50)   NULL  ,
	PRIMARY KEY ( `cedula` ) 
);
create table `servi_ot`.`tipoEquipo` ( 
 	`id_tipo_equipo` decimal   NOT NULL ,
	`nombTipoEquipo` varchar (50)   NULL  ,
	PRIMARY KEY ( `id_tipo_equipo` ) 
);
create table `servi_ot`.`usuarios` ( 
 	`id_usuario` varchar (20)   NOT NULL ,
	`password` varchar (20)   NOT NULL ,
	`nombre` varchar (80)   NOT NULL ,
	`estado` int (10)   NOT NULL  ,
	PRIMARY KEY ( `id_usuario` ) 
);
